### ISSUE TITLE
Hazelcast leader initiator hangs when submit new initiator to executorService

### ISSUE THREAD

**Issue by mixas27** [spring-cloud/spring-cloud-cluster#24] opened 2016-01-18 13:50 UTC
Hello,

I have 2 nodes cluster managed by hazelcast v. 3.5.4 and spring-cloud-cluster-hazelcast v. 1.0.0.1.M1.
After nodes worked in cluster during some time leader node was shut down and I expected that second node will become leader (method ```onGranted``` of my leader candidate will be called). But it not happend after a while.

Looks like thread hanged on submit new initiator to executorService. Here is staktrace
```
2016-01-18 12:56:41

"Hazelcast leadership" - Thread t@153
   java.lang.Thread.State: WAITING
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for <3dc44cf2> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
	- None
```

Can I fix it or is there any workarownd? 
Thanks in advance

**Comment by pperalta** [comment] 2016-01-19 15:22
Hello,

I was not able to reproduce this behavior. I ran two instances of this sample program:

```java
import com.hazelcast.core.Hazelcast;
import com.hazelcast.core.HazelcastInstance;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.cloud.cluster.leader.Candidate;
import org.springframework.cloud.cluster.leader.DefaultCandidate;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.Configuration;

/**
 * Sample Spring Boot application that demonstrates leader election
 * with the Spring Cloud leadership API using Hazelcast
 * as the underlying implementation.
 *
 * @author Patrick Peralta
 */
@Configuration
@ComponentScan
@EnableAutoConfiguration
public class HazelcastTestApplication {

	public static void main(String[] args) {
		SpringApplication.run(HazelcastTestApplication.class, args);
	}

	@Bean
	public Candidate candidate() {
		return new DefaultCandidate();
	}

	@Bean
	public HazelcastInstance hazelcastInstance() {
		return Hazelcast.newHazelcastInstance();
	}

	@Bean
	public LeaderInitiator initiator() {
		return new LeaderInitiator(hazelcastInstance(), candidate());
	}
}
```
The first instance logs:
```
2016-01-19 10:15:57.840  INFO 20610 --- [cast leadership] o.s.c.cluster.leader.DefaultCandidate    : DefaultCandidate{role=leader, id=d91bf07f-ab04-490e-acd0-25cf436ad03d} has been granted leadership; context: HazelcastContext{role=leader, id=d91bf07f-ab04-490e-acd0-25cf436ad03d, isLeader=true}
```
When I shut it down, the second one logs:
```
2016-01-19 10:16:30.390  INFO 20616 --- [cast leadership] o.s.c.cluster.leader.DefaultCandidate    : DefaultCandidate{role=leader, id=8663b3d7-ca3c-45c0-9d1c-d4e82b9f4d28} has been granted leadership; context: HazelcastContext{role=leader, id=8663b3d7-ca3c-45c0-9d1c-d4e82b9f4d28, isLeader=true}
```
Please provide specific instructions on how to reproduce and I'll be happy to look into it.

**Comment by mifmax** [comment] 2016-03-27 19:41
Hi. I reproduce this bug often, but don't always. My application use quartz and rabbit. In logs I found these strings:
`
19:08:59,605 +0000 [Hazelcast leadership] [SimpleMessageListenerContainer] [DEBUG] Starting Rabbit listener container.
19:08:59,605 +0000 [Hazelcast leadership] [SimpleMessageListenerContainer] [INFO] Consumers are already running
19:08:59,606 +0000 [Hazelcast leadership] [SimpleMessageListenerContainer] [DEBUG] No global properties bean
19:08:59,606 +0000 [Hazelcast leadership] [SimpleMessageListenerContainer] [DEBUG] Starting Rabbit listener container.
19:08:59,607 +0000 [Hazelcast leadership] [DefaultListableBeanFactory] [DEBUG] Returning cached instance of singleton bean 'rabbitAdmin'
`
`
19:08:59,672 +0000 [Hazelcast leadership] [SchedulerFactoryBean] [INFO] Starting Quartz Scheduler now
19:08:59,717 +0000 [Hazelcast leadership] [LocalDataSourceJobStore] [INFO] ClusterManager: detected 1 failed or restarted instances.
19:08:59,717 +0000 [Hazelcast leadership] [LocalDataSourceJobStore] [INFO] ClusterManager: Scanning for instance "MN-MSK6-RAZR81459105209099"'s failed in-progress jobs.
19:08:59,725 +0000 [Hazelcast leadership] [LocalDataSourceJobStore] [DEBUG] ClusterManager: ......Freed 0 acquired trigger(s).
19:08:59,726 +0000 [Hazelcast leadership] [LocalDataSourceJobStore] [DEBUG] ClusterManager: ......Deleted 0 complete triggers(s).
19:08:59,726 +0000 [Hazelcast leadership] [LocalDataSourceJobStore] [DEBUG] ClusterManager: ......Scheduled 0 recoverable job(s) for recovery.
19:08:59,726 +0000 [Hazelcast leadership] [LocalDataSourceJobStore] [DEBUG] ClusterManager: ......Cleaned-up 0 other failed job(s).
19:08:59,738 +0000 [Hazelcast leadership] [DataSourceUtils] [DEBUG] Returning JDBC Connection to DataSource
19:08:59,739 +0000 [Hazelcast leadership] [LocalDataSourceJobStore] [DEBUG] ClusterManager: Check-in complete.
19:08:59,740 +0000 [Hazelcast leadership] [LocalDataSourceJobStore] [DEBUG] JobStore background threads started (as scheduler was started).
`
Maybe it will help you understand why this is happening.

**Comment by mifmax** [comment] 2016-04-05 15:43
I can reproduce this error. If set parameter hazelcast.operation.call.timeout.millis very small, for example 100ms , then hazelcast throws exception about operation timeout:

`com.hazelcast.core.OperationTimeoutException: No response for 600 ms. Aborting invocation! Invocation{serviceName='hz:impl:lockService', op=com.hazelcast.concurrent.lock.operations.LockOperation{identityHash=329449634, serviceName='hz:impl:lockService', partitionId=258, replicaIndex=0, callId=0, invocationTime=1459864949624 (Tue Apr 05 17:02:29 MSK 2016), waitTimeout=9223372036854775807, callTimeout=100, namespace=DefaultObjectNamespace{service='hz:impl:mapService', objectName=spring-cloud-leader}}, partitionId=258, replicaIndex=0, tryCount=250, tryPauseMillis=500, invokeCount=5, callTimeout=100, target=Address[172.21.64.47]:5812, backupsExpected=0, backupsCompleted=0, connection=null} No response has been received!  backups-expected:0 backups-completed: 0
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.newOperationTimeoutException(Invocation.java:536) ~[Invocation.class:3.6.1]
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.waitForResponse(InvocationFuture.java:275) ~[InvocationFuture.class:3.6.1]
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.get(InvocationFuture.java:222) ~[InvocationFuture.class:3.6.1]
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.get(InvocationFuture.java:202) ~[InvocationFuture.class:3.6.1]
	at com.hazelcast.concurrent.lock.LockProxySupport.tryLock(LockProxySupport.java:136) ~[LockProxySupport.class:3.6.1]
	at com.hazelcast.concurrent.lock.LockProxySupport.tryLock(LockProxySupport.java:125) ~[LockProxySupport.class:3.6.1]
	at com.hazelcast.map.impl.proxy.MapProxyImpl.tryLock(MapProxyImpl.java:348) ~[MapProxyImpl.class:3.6.1]
	at com.panbet.core.cluster.CreditLeaderInitiator$Initiator.call(CreditLeaderInitiator.java:197) [CreditLeaderInitiator$Initiator.class:na]
	at com.panbet.core.cluster.CreditLeaderInitiator$Initiator.call(CreditLeaderInitiator.java:1) [CreditLeaderInitiator$Initiator.class:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
	at ------ End remote and begin local stack-trace ------.(Unknown Source) ~[na:na]
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveApplicationResponse(InvocationFuture.java:385) ~[InvocationFuture.class:3.6.1]
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveApplicationResponseOrThrowException(InvocationFuture.java:335) ~[InvocationFuture.class:3.6.1]
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.get(InvocationFuture.java:223) ~[InvocationFuture.class:3.6.1]
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.get(InvocationFuture.java:202) ~[InvocationFuture.class:3.6.1]
	at com.hazelcast.concurrent.lock.LockProxySupport.tryLock(LockProxySupport.java:136) ~[LockProxySupport.class:3.6.1]
	at com.hazelcast.concurrent.lock.LockProxySupport.tryLock(LockProxySupport.java:125) ~[LockProxySupport.class:3.6.1]
	at com.hazelcast.map.impl.proxy.MapProxyImpl.tryLock(MapProxyImpl.java:348) ~[MapProxyImpl.class:3.6.1]
	at com.panbet.core.cluster.CreditLeaderInitiator$Initiator.call(CreditLeaderInitiator.java:197) [CreditLeaderInitiator$Initiator.class:na]
	at com.panbet.core.cluster.CreditLeaderInitiator$Initiator.call(CreditLeaderInitiator.java:1) [CreditLeaderInitiator$Initiator.class:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
`

In method LeaderInitiator.Initiator.call() this exception don't catch. And we coming out this method... 

I was a little changed your test

  @Bean
    public HazelcastInstance hazelcastInstance()
    {
        Config config = new Config();
        config.setProperty("hazelcast.port", "5812");
        config.setProperty("hazelcast.port.autoincrement", "true");
        config.setProperty("hazelcast.network.multicast.enabled", "true");
        config.setProperty("hazelcast.network.multicast.group", "224.2.2.3");
        config.setProperty("hazelcast.network.multicast.port", "54438");
        config.setProperty("hazelcast.network.tcp.ip.enabled", "false");
        config.setProperty("hazelcast.network.tcp.ip.members", "127.0.0.1");
        config.setProperty("hazelcast.client.heartbeat.interval", "300");
        config.setProperty("hazelcast.client.heartbeat.timeout", "5000");
        config.setProperty("hazelcast.client.max.no.heartbeat.seconds", "5");

        config.setProperty("hazelcast.operation.call.timeout.millis", "50");

        config.setProperty("hazelcast.member.list.publish.interval.seconds", "10");
        config.setProperty("hazelcast.merge.first.run.delay.seconds", "5");
        config.setProperty("hazelcast.merge.next.run.delay.seconds", "1");
        config.setProperty("hazelcast.max.wait.seconds.before.join", "3");
        config.setProperty("hazelcast.initial.min.cluster.size", "1");
        return Hazelcast.newHazelcastInstance(config);
    }


And now this bug reproduced

After this warnings in your test class

`2016-04-05 18:36:40.911  WARN 52500 --- [cast leadership] c.h.s.i.o.impl.Invocation                : [172.21.64.50]:5702 [profiling] [3.6.1] No response for 107 ms. InvocationFuture{invocation=Invocation{serviceName='hz:impl:lockService', op=com.hazelcast.concurrent.lock.operations.LockOperation{identityHash=41949160, serviceName='hz:impl:lockService', partitionId=258, replicaIndex=0, callId=3, invocationTime=1459870600772 (Tue Apr 05 18:36:40 MSK 2016), waitTimeout=9223372036854775807, callTimeout=50, namespace=DefaultObjectNamespace{service='hz:impl:mapService', objectName=spring-cloud-leader}}, partitionId=258, replicaIndex=0, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeout=50, target=Address[172.21.64.50]:5701, backupsExpected=0, backupsCompleted=0, connection=Connection [/172.21.64.50:5702 -> /172.21.64.50:64282], endpoint=Address[172.21.64.50]:5701, alive=true, type=MEMBER}, response=null, done=false}
2016-04-05 18:36:40.912  WARN 52500 --- [cast leadership] c.h.s.i.o.impl.Invocation                : [172.21.64.50]:5702 [profiling] [3.6.1] Asking if operation execution has been started: Invocation{serviceName='hz:impl:lockService', op=com.hazelcast.concurrent.lock.operations.LockOperation{identityHash=41949160, serviceName='hz:impl:lockService', partitionId=258, replicaIndex=0, callId=3, invocationTime=1459870600772 (Tue Apr 05 18:36:40 MSK 2016), waitTimeout=9223372036854775807, callTimeout=50, namespace=DefaultObjectNamespace{service='hz:impl:mapService', objectName=spring-cloud-leader}}, partitionId=258, replicaIndex=0, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeout=50, target=Address[172.21.64.50]:5701, backupsExpected=0, backupsCompleted=0, connection=Connection [/172.21.64.50:5702 -> /172.21.64.50:64282], endpoint=Address[172.21.64.50]:5701, alive=true, type=MEMBER}
2016-04-05 18:36:40.925  WARN 52500 --- [cast leadership] c.h.s.i.o.impl.Invocation                : [172.21.64.50]:5702 [profiling] [3.6.1] 'is-executing': false -> Invocation{serviceName='hz:impl:lockService', op=com.hazelcast.concurrent.lock.operations.LockOperation{identityHash=41949160, serviceName='hz:impl:lockService', partitionId=258, replicaIndex=0, callId=3, invocationTime=1459870600772 (Tue Apr 05 18:36:40 MSK 2016), waitTimeout=9223372036854775807, callTimeout=50, namespace=DefaultObjectNamespace{service='hz:impl:mapService', objectName=spring-cloud-leader}}, partitionId=258, replicaIndex=0, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeout=50, target=Address[172.21.64.50]:5701, backupsExpected=0, backupsCompleted=0, connection=Connection [/172.21.64.50:5702 -> /172.21.64.50:64282], endpoint=Address[172.21.64.50]:5701, alive=true, type=MEMBER}
2016-04-05 18:36:41.069  WARN 52500 --- [filing.response] com.hazelcast.spi.OperationService       : [172.21.64.50]:5702 [profiling] [3.6.1] No Invocation found for response: CallTimeoutResponse{callId=3, urgent=false} sent from Address[172.21.64.50]:5701
`
Thread leaderShip falls

**Comment by pperalta** [comment] 2016-04-13 14:45
Thank you for your update; I was able to reproduce this. Working on a fix now.

**Comment by dsyer** [comment] 2016-04-18 14:58
@mifmax please use fences (three ticks) for multiline code content and logs.

**Comment by dsyer** [comment] 2016-04-18 15:03
#28 is merged, but it wasn't clear from the comments if that was a fix for this or not, so I'm leaving it open. Maybe @pperalta you could close this one and mark it for 1.0.0.RC2 if it's fixed?

**Comment by mifmax** [comment] 2016-04-18 15:10
@dsyer, Yes ok. Thank you for your comment. I'm sure that commit correct the error.

**Closed** 2016-04-18 15:12 UTC
